### ISSUE TITLE
Very stupidly easy error, but just can't seem to fix

### ISSUE THREAD

**Issue by TheMajesticMagician** [stanjg/Ptero4J#15]
This is my error
`Ptero4J loaded! Successfully made contact with the panel.
Exception in thread "main" java.lang.NoSuchMethodError: org.json.JSONObject.keySet()Ljava/util/Set;
	at com.stanjg.ptero4j.entities.objects.server.ServerContainer.getEnvironmentVariablesMap(ServerContainer.java:32)
	at com.stanjg.ptero4j.entities.objects.server.ServerContainer.<init>(ServerContainer.java:27)
	at com.stanjg.ptero4j.entities.objects.server.ServerContainer.<init>(ServerContainer.java:15)
	at com.stanjg.ptero4j.entities.panel.admin.Server.<init>(Server.java:39)
	at com.stanjg.ptero4j.controllers.admin.ServersController.getNewInstance(ServersController.java:70)
	at com.stanjg.ptero4j.controllers.admin.ServersController.getNewInstance(ServersController.java:18)
	at com.stanjg.ptero4j.controllers.admin.ResourceController.addPageToList(ResourceController.java:266)
	at com.stanjg.ptero4j.controllers.admin.ResourceController.getAllResources(ResourceController.java:204)
	at com.stanjg.ptero4j.controllers.admin.ServersController.getAllServers(ServersController.java:41)
	at Test.main(Test.java:21)
`
And this is my code
`import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.List;
import com.stanjg.ptero4j.PteroAdminAPI;
import com.stanjg.ptero4j.controllers.admin.ServersController;
import com.stanjg.ptero4j.controllers.admin.UsersController;
import com.stanjg.ptero4j.entities.panel.admin.Server;
import com.stanjg.ptero4j.entities.panel.admin.User;

public class Test {
	
	public static void main(String[] args) {
		PteroAdminAPI api = new PteroAdminAPI("http://panel.themajesticnetwork.com/", "s4nCuW6BAacGTcUQVXtq559AR6UrqhUyWm8LiZxIcrUlanwH");

        // Then fetch the server using the ServersController
        ServersController servers = api.getServersController();

        List<Server> server = servers.getAllServers();
        
        List<Server> serverPage = servers.getServerPage(1);
        
        
        
        UsersController usersController = api.getUsersController();
        List<User> users = usersController.getUsers("search");
    	try{
    	  
    		String serverSection = "SYHAT";
    		String userSection = "UYA";
      	  // Create file 
      	  FileWriter fstream = new FileWriter("details.txt");
      	  BufferedWriter out = new BufferedWriter(fstream);
      	  out.write(serverSection + ": " + serverPage);
      	  
      	  
      	  //Close the output stream
      	  out.close();
      	  }catch (Exception e){//Catch exception if any
      	  System.err.println("Error: " + e.getMessage());
      	  }
	}
	
	
}
`
And I cant seem to find out how to fix this, help me please.

**Comment by TheMajesticMagician** [comment]
I resolved my issue, just had to get the source code, and fix the errors there, and change the json.KeySet() to the gson JsonObject.keySet() version
